dist: xenial

language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - sudo apt-get install -y pylint3
    - sudo apt-get install -y python3-pip
    - pip install coverage
    - pip install codecov
    - pip install mypy

script:
    - python -V
    - python3 -V
    - python3 -m unittest discover tests/
    - python3 -m mypy ./gingerfy/
    - pylint3 ./gingerfy/
    - coverage run --source gingerfy/ -m unittest discover tests/

after_success:
    - codecov
