dist: xenial

language: python

python:
    - "3.6"
    - "3.7"

install:
    - sudo apt-get install -y pylint
    - sudo apt-get install -y python-pip
    - pip install coverage
    - pip install codecov

script:
    - python -m unittest discover tests/
    - pylint ./gingerfy/
    - coverage run --source gingerfy/ -m unittest discover tests/

after_success:
    - codecov
